# Generated by Django 4.1.13 on 2024-03-12 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='publication',
            name='publish_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
